ethereum_smartcontract.contract.*:
  type: config_entity
  label: 'Smart Contract config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    contract_src:
      type: string
      label: 'Contract Source file (relative path to ethereum_smartcontract directory).'
    contract_compiled_json:
      type: string
      label: 'Compiled contract JSON as provided by solidity compiler (solc).'
    networks:
      type: sequence
      label: 'Contract addresses by network id.'
      sequence:
        -  type: string
           label: '<network_id> => <contract address>'
