ethereum_smartcontract.contract.*:
  type: config_entity
  label: 'Smart Contract config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    contract_src:
      type: string
      label: 'Contract Source file (relative path to ethereum_smartcontract directory).'
    contract_json:
      type: string
      label: 'Compiled contract Javascript file (relative path to ethereum_smartcontract directory).'
