ethereum.ethereum_server.*:
  type: config_entity
  label: 'Ethereum-Node servers'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    url:
      type: uri
      label: 'Ethereum server url.'
    network_id:
      type: string
      label: 'Ethereum Network ID'
    is_enabled:
      type: boolean
      label: 'Networks will be ignored entirely if not enabled.'
    description:
      type: text
      label: 'Description'
