ethereum.ethereum_server.*:
  type: config_entity
  label: 'Ethereum Node server'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    url:
      type: uri
      label: 'Ethereum server url'
    network_id:
      type: string
      label: 'Ethereum Network ID'
